version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - '5432:5432'
    networks:
      - app_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - app_net
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - app_net
  nginx: 
    image: reverse-proxy
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${NGINX_HOST}
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - app
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
